### PR TITLE
Making @atomic robust

### LINKED ISSUE #453: @atomic does not error nicely
```
julia> @cuda ((a)->(CUDAnative.@atomic a[2] = 42; nothing))(CuArray{Int}(undef, 1))
ERROR: LoadError: type Int64 has no field head
```

### PR DESCRIPTION
**Pull request by UmashankarTriforce**
This PR aims to handle various errors encountered by `@atomic` and report them nicely
Fixes #453

### CODE REVIEW

**Comment by UmashankarTriforce** [comment]
I would like to know what other conditions I need to check for. Hence I have added `[WIP]` in PR.

**Comment by UmashankarTriforce** [comment]
Where and how do I add a test?

**Comment by maleadt** [comment]
Have a look at the `tests/` folder, there's a bunch of existing ones for `@atomic`.

**Comment by UmashankarTriforce** [comment]
I have added a section for `exception` test and accomodated the previous failing case. Let me know if I have missed out on something

File: src/device/cuda/atomics.jl [hunk 1]
```diff
@@ -319,6 +319,9 @@ macro atomic(ex)
     if ex.head == :(=)
         ref = ex.args[1]
         rhs = ex.args[2]
+        if typeof(rhs) <: Number || typeof(rhs) <: String || typeof(rhs) <: Symbol
```
Comment (maleadt) [inline src/device/cuda/atomics.jl]: That's not what I meant, instead of checking against a blacklist of non-Expr types, it's easier to (whitelist) check for what's allowed: `Expr`.

File: test/device/cuda.jl [hunk 2]
```diff
@@ -981,6 +981,18 @@ end
...
+        a = CuArray([typemax(T)])
+        function kernal(T, a)
+            @atomic a[1] = 1
+            @atomic a[1] = "1"
+            @atomic a[1] = i
+            return
+        end
+        @cuda threads=32 kernal(T, a)
+        @test Array(a)[1] == 1
+    end
```
Comment (maleadt) [inline test/device/cuda.jl]: Did you run these tests? They are intended to fail, so you can't just run them (the test would fail). Instead, you need to `test_throws`. Also, you can't put multiple failing atomic expressions in a single test because it'll bail out at the first error.
I'll push a fix, since it's somewhat finicky to use `test_throws` with macros.

**Comment by maleadt** [comment]
bors try

File: src/device/cuda/atomics.jl (hunk 1 above)
Comment (UmashankarTriforce) [reply src/device/cuda/atomics.jl]: Ahh okay I'll fix this

File: test/device/cuda.jl (hunk 2 above)
Comment (UmashankarTriforce) [reply test/device/cuda.jl]: I did test them, but they didn't throw any error

**Comment by maleadt** [comment]
Let's merge this. Thanks for the PR!
